### ISSUE TITLE
Validate National ID with Persian/Arabic Numbers

### ISSUE THREAD

**Issue by ShahriarKh** [persian-tools/persian-tools#102]
Currently, only English numbers can be used to validate the national id.
Is there a way to accept Persian/Arabic numbers **without converting** the number?

```
verifyIranianNationalId("0499370899"); // true
verifyIranianNationalId("۰۴۹۹۳۷۰۸۹۹"); // false
verifyIranianNationalId("٠٤٩٩٣٧٠٨٩٩"); // false
```

**Comment by ali-master** [comment]
Hi there,

No, because it is a pure function that works with English numbers well, You should convert digits to English before passing to the function by using `digitsArToEn` or `digitsFaToEn`.

**Comment by ShahriarKh** [comment]
Thanks

One last question: Will the functionality be implemented in the future to avoid writing custom functions? I guess this function will be mostly used in from inputs for validation, so it will be really great if "persian-tools" do it by default.

**Comment by ali-master** [comment]
If I wanna be honest, No. Because pure function should just do one task. this is a strict rule of pure functions.
