### ISSUE TITLE
How is "addCommas" different from "toLocaleString()"?

### ISSUE THREAD

**Issue by ShahriarKh** [persian-tools/persian-tools#104]
This is a question, not an issue.
In JS, we can easily add commas with `(number).toLocaleString()`. While both this and `addCommas(number)` both accept only English numbers and do the same thing, what is the real difference between them? Which one should I use?

**Comment by pshaddel** [comment]
@ShahriarKh Hi Shahriar
As far as I'm concerned `.toLocalString()` is not working on strings and as a result it is not going to work on Persian numbers so I guess that's why `addCommos` is implemented. The source code of this function might give you a clue about what's going on:
```typescript
import { digitsFaToEn } from "../digits";
import { isPersian } from "../isPersian";

/**
 * Add Commas to numbers
 *
 * @method addCommas
 * @param {number} number, eg: 300000
 * @return {string} string of separated numbers by commas, eg: 30,000
 */
const addCommas = (number: number | string): string => {
	if (typeof number !== "number" && typeof number !== "string") return "";

	const convertedToString = number.toString();
	const tokenizedToEnglish = isPersian(convertedToString)
		? (digitsFaToEn(convertedToString) as string)
		: convertedToString;

	const tokenizedNumber = tokenizedToEnglish.split(".");
	const integer = tokenizedNumber[0].replace(/(\d)(?=(\d{3})+(?!\d))/g, "$1,");
	const decimal = tokenizedNumber[1] ? `.${tokenizedNumber[1]}` : "";

	return integer + decimal;
};

export default addCommas;
```

Also you can use [this link](https://github1s.com/persian-tools/persian-tools/blob/HEAD/src/modules/commas/add.ts#L1-L27) to see other functions.

**Comment by mediv0** [comment]
- `toLocaleString` does not work with string values
```js
const num = "100000000";
num.toLocaleString();       // 100000000
PersianTools.addCommas(num);     // 100,000,000
```

- `addCommas` is 15x faster than `toLocaleString`   [check](https://jsben.ch/Fbs0q)
- `toLocaleString` returns a string with the language-sensitive representation of a number

take this for example:
```js
const number = 3500.2;

// German uses comma as decimal separator and period for thousands
console.log(number.toLocaleString('de-DE'));
// →  3.500,2 !!!!

//  English version:
// → 3,500.2
```

`addCommas` will always return the same output

**Comment by ShahriarKh** [comment]
Thanks!
I believe there should be examples of using `addCommas` with Persian numbers in the Readme. Honestly, by just checking the examples provided I thought it can only be used with English numbers.
