### ISSUE TITLE
accountNumber in parsed shebaCode becomes undefined

### ISSUE THREAD

**Issue by theMasix** [persian-tools/persian-tools#106]
**Describe the bug**
Sometime `accountNumber` and `formattedAccountNumber` in parsed shebaCode becomes `undefined`

**To Reproduce**
1. use `recognize` to parse shebaCode

**Expected behavior**
if `accountNumberAvailable` is true, then `accountNumber` and `formattedAccountNumber` should be available.

**Example**

![image](https://user-images.githubusercontent.com/22872117/129893220-081f1aef-80f6-4f2a-a145-11702bafdd24.png)

NOTE: I have faced with this issue using Pasargad Bank shebaCode.

**Additional context**
Package Version: `1.7.1`

**Comment by ali-master** [comment]
Thanks for reporting this bug, it is fixed now and released in v1.8.0-beta.0 as a beta version. The Sheba class has changed and now it is 3 functions:
1. `getShebaInfo`
2. `shebaIso7064Mod97`(You've no need to use this function)
3. `isShebaValid`

Usage:
```bash
npm i --save @persian-tools/persian-tools@beta
```

**Comment by ghonchesefidi** [comment]
So please consider updating this in docs too. currently using:  
`import { Sheba } from "@persian-tools/persian-tools";`   
Will give error.
    "@persian-tools/persian-tools": "^1.8.0-beta.0",

**Comment by ghonchesefidi** [comment]
As it is a major change and it's breaking the API, I think you should increase the version number(2.0.0) if you are committed to semantic versioning.

**Comment by ali-master** [comment]
> So please consider updating this in docs too. currently using:
> `import { Sheba } from "@persian-tools/persian-tools";`
> Will give error.
> "@persian-tools/persian-tools": "^1.8.0-beta.0",

I know, and I released a beta version.

**Comment by ali-master** [comment]
> As it is a major change and it's breaking the API, I think you should increase the version number(2.0.0) if you are committed to semantic versioning.

We should refactor some functions and after that, I'll release the v2.0.0 after about 4 years.

**Comment by ghonchesefidi** [comment]
> > So please consider updating this in docs too. currently using:
> > `import { Sheba } from "@persian-tools/persian-tools";`
> > Will give error.
> > "@persian-tools/persian-tools": "^1.8.0-beta.0",
> 
> I know, and I released a beta version.

Good. I don't know why I have got 1.8.0-beta.0 when installing it from NPM!
I think we have some sort of conflict here.
If you upgrade the package to the next version, everything is fine, BUT as you have implemented these changes in this beta version all your npm users will get these changes on the next 1.8.X update and it might break their app.
So please clarify if I'm wrong?

**Comment by ali-master** [comment]
> > > So please consider updating this in docs too. currently using:
> > > `import { Sheba } from "@persian-tools/persian-tools";`
> > > Will give error.
> > > "@persian-tools/persian-tools": "^1.8.0-beta.0",
> > 
> > 
> > I know, and I released a beta version.
> 
> Good. I don't know why I have got 1.8.0-beta.0 when installing it from NPM!
> I think we have some sort of conflict here.
> If you upgrade the package to the next version, everything is fine, BUT as you have implemented these changes in this beta version all your npm users will get these changes on the next 1.8.X update and it might break their app.
> So please clarify if I'm wrong?

You're right, It is my fault and I should update the README and create the v2.0.0 version and release it until tomorrow.

**Comment by ghonchesefidi** [comment]
Thanks for your update, Ali. I think we can close this issue now. @ali-master
