### ISSUE TITLE
wordToNumber is returning zero for hezar

### ISSUE THREAD

**Issue by saeedalipoor** [persian-tools/persian-tools#107]
‎`wordsToNumber('هزار')`
returns 0 but should return 1000

**Comment by ali-master** [comment]
Hi Saeed Jan

What is the output of ‎```numberToWords(1000)```? I guess, `یک هزار`
This condition should be applied just to Numbers by multiples of thousands, hundreds to return the result as well as we expect.

**Comment by saeedalipoor** [comment]
Hi Ali
Yes, you're right, and also wordToNumber is working correctly for hundred.
Thanks

**Comment by ali-master** [comment]
Hi @saeedalipoor Jan,

@mediv0 has created a PR related to this issue and after checking all possible test cases, we will release a new version.
