### ISSUE TITLE
addCommas return Undefiend

### ISSUE THREAD

**Issue by theMasix** [persian-tools/persian-tools#11]
Hello. Thanks for great library.
But there is an issue with the ```addCommas``` function. If I use ```addCommas``` on 0 number, it returns ```undefiend``` which I think it should return that 0 instead.
```
addCommas(0) // undefiend
```

**Comment by ali-master** [comment]
Hi @theMasix,

Thanks for using the library.
The reported bug has been fixed and release in v1.2.2.

Try ```npm update``` or use ```npm-check-updates``` package

**Comment by theMasix** [comment]
@ali-master Yeah thanks. it is solved now.
