### ISSUE TITLE
new feature

### ISSUE THREAD

**Issue by meiti-x** [persian-tools/persian-tools#114]
توی پروژه من یه بررسی کردم الگوریتمی برای تایید صحت شناسه ملی افراد حقوقی نداریم.

[الگوریتم بررسیش](http://www.aliarash.com/article/shenasameli/shenasa_meli.htm)
اگر اوکیه بنظرت و نداریمش. بسپارش به من و اضافه میکنم :)

**Comment by ali-master** [comment]
سلام مهدی جان

مرسی از پیشنهادت و اگر دوست داری، شروعش کن
