### ISSUE TITLE
Add Method to convert Number to Persian Ordinal Words

### ISSUE THREAD

**Issue by theMasix** [persian-tools/persian-tools#12]
Hello. Thanks for great project.
It would be great if the library has a method to convert Number to Persian Ordinal Words.
Like ```3``` to ```سوم``` or ```5826``` to ```پنج هزار و هشت‌صد و بیست و ششم```

**Comment by ali-master** [comment]
Hi there

Thanks for using it.
Can you provide more samples?

**Comment by theMasix** [comment]
@ali-master You can check [List of Ordinal Numbers in Persian](http://mylanguages.org/persian_numbers.php)
and [اعداد ترتیبی](https://fa.wikipedia.org/wiki/%D8%A7%D8%B9%D8%AF%D8%A7%D8%AF_%D8%AA%D8%B1%D8%AA%DB%8C%D8%A8%DB%8C_(%D8%B2%D8%A8%D8%A7%D9%86%E2%80%8C%D8%B4%D9%86%D8%A7%D8%B3%DB%8C))

Suprisingly, there is no library that converts Integer to Ordinal Numbers in Persian!
And unfortunately, the algorithm is more complicated that simple Persian numbers ...
