### ISSUE TITLE
(method) String.substr(from: number, length?: number): string , deprecated !

### ISSUE THREAD

**Issue by pooooriya** [persian-tools/persian-tools#125]
Hi, thanks for this cool package and for supporting the Iranian open source community
In verifyIranianNationalId function TSlint said (method) String.substr(from: number, length?: number): string was deprecated 

**Screenshots**
![image](https://user-images.githubusercontent.com/65160744/147918767-e086488f-4656-418c-bb57-376430577b30.png)

**Desktop (please complete the following information):**
 - OS:Windows 11
 - Browser Chrome
 - Version 96

**Comment by moh3n9595** [comment]
dear @M0rteza-M, Can you use an alternative method in your current PR? #123

**Comment by M0rteza-M** [comment]
Yes, I replaced `substr() `with `substring() `method.

**Comment by ali-master** [comment]
v3.2.0 published
