### ISSUE TITLE
nationalcode validation maybe need review 

### ISSUE THREAD

**Issue by pooooriya** [persian-tools/persian-tools#139]
Hi again, 
in the validation of national code when user type 1111111111 or 222222222 or any same numbers 
the function returns true, but actually, its the wrong national code, and no one has this national code, maybe need to check another condition to check if all numbers same then return false 

**Expected behavior**
return false

**Comment by pooooriya** [comment]
no need for change :))))
https://www.iranjib.ir/shownews/56644/%D8%B5%D8%A7%D8%AD%D8%A8-%D8%B4%D9%85%D8%A7%D8%B1%D9%87-%DA%A9%D8%AF%D9%85%D9%84%DB%8C-%DB%B1%DB%B1%DB%B1%DB%B1%DB%B1%DB%B1%DB%B1%DB%B1%DB%B1%DB%B1-%DA%A9%DB%8C%D8%B3%D8%AA%D8%9F/

**Comment by pooooriya** [comment]
Review this #140

**Comment by moh3n9595** [comment]
Just `111111111111` is a valid national id, and it's not about all the same numbers in a row national ids like `2222222222`.

**Comment by pooooriya** [comment]
This cannot be said because maybe those numbers were also made but no one published any news, so reason dictates that this condition be removed, of course, as you know.
