### ISSUE TITLE
better CI/CD

### ISSUE THREAD

**Issue by moh3n9595** [persian-tools/persian-tools#15]
Since your Travis build has some errors, it can be awesome if `persian-tools` switch to CircleCI or GitHub actions or even more accurate continuous integrated flow with Travis. Codcov can be added for better detection in code coverage as well as.

**Comment by ali-master** [comment]
I'm absolutely agreed with your idea, I implemented the Travis CI for about 3 years ago and Github Actions is more useful and easy to work and very comfortable with the Github repositories.

So, Do you have enough time to do that?

**Comment by moh3n9595** [comment]
Yes, of course, but I don't have the right access to `persian-tools` Github Actions now

**Comment by ali-master** [comment]
I sent you an invitation as a collaborator.

**Comment by moh3n9595** [comment]
Seems the problem is resolved after b16c9fe530344de5327766ae6a5588b7909be728.
I'm going to close the issue.
