### ISSUE TITLE
For Jalali and Gregorian date converter

### ISSUE THREAD

**Issue by shahabfar** [persian-tools/persian-tools#29]
**Is your feature request related to a problem? Please describe.**
No.

To convert Jalali and Gregorian dates to each other you can find the source from my library [here ](https://github.com/shahabfar/Persia-.NET-Core)which is the precise conversion for Jalali, Gregorian, and Islamic (moon) date.

**Comment by ali-master** [comment]
Hi @shahabfar

I saw your repo and I'm impressed, well done.

I'll start implementing your repo in js.
