### ISSUE TITLE
timeago calculate wrong date

### ISSUE THREAD

**Issue by pooooriya** [persian-tools/persian-tools#292]
**Describe the bug**
![image](https://user-images.githubusercontent.com/65160744/198694605-30d1abd3-649e-40eb-b5c2-a93044e820e9.png)

**Expected behavior**
no need to calculate after a time or you can estimate all +1 minute to now 

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11 
 - chrome
 - lastest
 

**Smartphone (please complete the following information):**

**Additional context**
![image](https://user-images.githubusercontent.com/65160744/198695026-7281742f-d252-40a8-97fa-1358de888291.png)
this is my implementation

**Comment by pooooriya** [comment]
![image](https://user-images.githubusercontent.com/65160744/198696813-866f46b8-3c4f-4e4f-bf76-389c6a0a9b84.png)
1.         let elapsed = tsTimeNow - tsDateTime;
2.       console.log(tsDateTime); // inside code base
3.      console.log(datetime); // current datetime

**Comment by pooooriya** [comment]
i rewrite my code again with this solution 
![image](https://user-images.githubusercontent.com/65160744/198700032-7a9c2878-b736-4803-be76-1a08fbf1dd0f.png)

but it give me +1 seconds again

**Comment by ali-master** [comment]
Thanks for reporting and fixing the bug. I really appreciate it.

**Comment by pooooriya** [comment]
I had an issue when committing my changes 
prettier got an error and it couldn't find the target files 
I fix it when adding some "" in the package json command section
I didn't send this change 
![image](https://user-images.githubusercontent.com/65160744/199191191-65f8af45-35d3-4992-8cfc-ee24fcbb522f.png)
![image](https://user-images.githubusercontent.com/65160744/199191378-f54454c7-07aa-4f0a-9ba3-ab717daaafff.png)

**Comment by pooooriya** [comment]
any updates ? @ali-master

**Comment by ali-master** [comment]
> I had an issue when committing my changes 
> prettier got an error and it couldn't find the target files 
> I fix it when adding some "" in the package json command section
> I didn't send this change 
> can you check it in your system 
> maybe after merging packages update with update bot 
> some expected behavior doesn't work anymore
> ![image](https://user-images.githubusercontent.com/65160744/199191191-65f8af45-35d3-4992-8cfc-ee24fcbb522f.png)
> ![image](https://user-images.githubusercontent.com/65160744/199191378-f54454c7-07aa-4f0a-9ba3-ab717daaafff.png)
> 
> 

We have no compatibility with Windows, I suggest you use the WSL and run the Ubuntu in windows.
