### ISSUE TITLE
Per Method Packages

### ISSUE THREAD

**Issue by ammoradi** [persian-tools/persian-tools#30]
As you know, [lodash](https://www.npmjs.com/package/lodash) has a capability to import [modularized](https://www.npmjs.com/search?q=keywords:lodash-modularized) sub-packages called [per method packages](https://github.com/lodash/lodash#module-formats)
It is good for you to make this package modularized especially for the **independent functionalities**.
for example when a project only needs one of these package functionalities e.g. `Sheba`, it is better to add and import it like this:
```
yarn add persian-tools.sheba
```
```js
import Sheba from 'persian-tools.sheba'
```

this approach is good for minimizing projects bundle size when using this package because many projects don't need all of these package functionalities

**Comment by ali-master** [comment]
Hi @ammoradi 

What a good point, I thought a few days ago to refactor the Persian-Tools in order to convert all modules to a standalone module.

So, My suggestion to do the idea is to use the `Lerna`. Do you have a better idea?

**Comment by ali-master** [comment]
For your information, I've created the Persian-Tools organization in the `NPM`, and in the next release, the Persian-tools package path will be:
```
$ npm i --save @persian-tools/persian-tools
```

**Comment by ammoradi** [comment]
@ali-master  I didn't use `Lerna` yet. I will investigate the ways to do this modularization and will mention here if I find a good way

**Comment by ali-master** [comment]
I appreciate your help and attention.

**Comment by moh3n9595** [comment]
If you import or require methods directly, e.g. `const sheba = require('persian-tools2/sheba')`, only the subset of `persian-tools2` your package uses will be bundled in projects that use your package.
So another way can be that.
