### ISSUE TITLE
get bank name by account_number

### ISSUE THREAD

**Issue by tabeshR** [persian-tools/persian-tools#31]
Hi every one,
thank you very much to this very good project.
if we could find bank name by account number (شماره حساب)
It will be great
if it's possible please added
thanks alot again

**Comment by ali-master** [comment]
Hi @tabeshR 

This feature is already implemented and published in v1.5.0.

Check it out: [Iranian IBan](https://github.com/persian-tools/persian-tools#iranian-shebaiban)

**Comment by tabeshR** [comment]
ببخشید من نتونستم منظورم رو برسونم
منظورم اینه که شماره حساب بدهیم و اطلاعات بانک را برگردانیم
نه شماره شبا را
مثلا
020817909002
را بدهیم و اطلاعات برگردد

**Comment by ali-master** [comment]
به موضوع جالبی اشاره کردی و تمامی بانک هایی که طرف قرارداد با داتین و توسن هستن رو میشه یکسری اطلاعات مثل، کد شعبه، کد مشتری، نام بانک و یک مورد دیگه که یادم نیست رو از روی شماره متوجه شد.
اما بانک هایی که طرف قرارداد با خدمات انفورماتیک هستن این قابلیت رو ندارن و از قانون جدید شماره حساب ها پیروی نمی کنن متاسفانه.

من الگوی استخراج این اطلاعات رو مینویسم اینجا و خودت اگر خواستی میتونی کدش رو بنویسی یا اینکه من اگر وقت کردم بنویسمش که بعید میدونم فعلا وقت کنم راستش.

**Comment by tabeshR** [comment]
دستت درد نکنه هر وقت گذاشتی حتما استفاده میکنم

**Comment by pshaddel** [comment]
@ali-master 
سلام علی آقا 
فک کنم بتونم تو بستن این ایشو کمک کنم.
الگوی استخراج اینا رو از کجا پیدا کنم؟

**Comment by ali-master** [comment]
@pshaddel 
سلام پورشاد جان،

من الگویی که بهش رسیدم رو با مدیر تیم بانکیمون نهایی میکنم و برات همینجا میفرستم که بتونی شروعش کنی.

خوشحالم که میخوای به تیممون بپیوندی.

**Comment by pshaddel** [comment]
@ali-master 
سلام علی جان - این الگو رو میفرستی اینجا؟

**Comment by ali-master** [comment]
ببخشید بابت تاخیر، فراموش کردم کلا

چشم، روی یک کاغذی نوشته بودم فرمتش رو، پیداش میکنم و میفرستمش

**Comment by pshaddel** [comment]
> ببخشید بابت تاخیر، فراموش کردم کلا
> 
> چشم، روی یک کاغذی نوشته بودم فرمتش رو، پیداش میکنم و میفرستمش

خواهش میکنم منم یادم رفته بود تصادفی میجرخیدم تو ایشو ها یادم اومد. دمت گرم

**Comment by ali-master** [comment]
من بازم کلی گشتم و به این نتایج رسیدم:

234-800-1415570-1
به ترتیب از چپ به راست
•  کد شعبه – ماکزیمم 4 رقم
•  نوع حساب -  ماکزیمم 4 رقم
•  شماره مشتری – ماکزیمم 8 رقم
•  شمارنده حساب از همان نوع – ماکزیمم 2 رقم

در هر بانکی کد نوع حساب متفاوت هست و نمیشه استانداردی داشته باشه
مثلا 100 در پاسارگاد حساب جاری  هست ولی در سامان این کد حساب  20 هست
به همین دلیل هم هست که هیچ وقت از حساب یه بانک به حساب بانک دیگه نمیتونید واریز کنید و باید با شبا این کارو بکنید

**Comment by pshaddel** [comment]
> در هر بانکی کد نوع حساب متفاوت هست و نمیشه استانداردی داشته باشه

پس یعنی نمیشه به این راحتی فهمید شماره حساب مثلا مربوط به کدوم بانک یا شعبه ست؟
 ما میخوایم یه سرویسی شبیه به این بنویسیم:
[bank api service](https://www.finnotech.ir/fa/Service/Detail/16/%D8%A7%D8%B3%D8%AA%D8%B9%D9%84%D8%A7%D9%85-%DA%A9%D8%A7%D8%B1%D8%AA)

**Comment by ali-master** [comment]
ما نمیتونیم به سرویس های بانکی وصل بشیم و فینوتک پشتش بانک آینده هستش و از خودش چیزی نداره.
