### ISSUE TITLE
`verifyIranianNationalId` util doesn't validate correctly

### ISSUE THREAD

**Issue by Sinakhx** [persian-tools/persian-tools#337]
The `verifyIranianNationalId` util's algorithm does not work correctly. It validates some wrong national IDs as valid.

```js
const { verifyIranianNationalId } = require('@persian-tools/persian-tools');

const ID1 = '0123456789';
const isID1Valid = verifyIranianNationalId(ID1);
console.log('isID1Valid:', isID1Valid);

const ID2 = '1234567891';
const isID2Valid = verifyIranianNationalId(ID2);
console.log('isID2Valid:', isID2Valid);
```

logs:

```
isID1Valid: true
isID2Valid: true
```

[link to runkit](https://runkit.com/sinakhx/64e4c4f1d9df0d0008a2b6f7)

**Comment by pshaddel** [comment]
@Sinakhx Could you clarify why this one is wrong? I mean which logic is not right there.

**Comment by Sinakhx** [comment]
@pshaddel as you can see, the sequence of numbers from zero to nine (`0123456789`) should not be a valid national ID. No City or province in Iran resembles the starting pattern of `012`. we can also write similar random numbers for which the current implementation returns false positive.

**Comment by pshaddel** [comment]
@Sinakhx Thanks! Got it. I think this link would be helpful, it contains a list of cities and the codes which are allowed. 
http://sinazanjan.blogfa.com/post/37

https://gist.github.com/Gictorbit/a1cf425041b90ffb15fa11343a752f2f

I would prepare the PR in the mean time.

**Comment by Sinakhx** [comment]
@pshaddel I appreciate your support. Thanks in advance :pray:
