### ISSUE TITLE
Error handling issue

### ISSUE THREAD

**Issue by masoudDaliriyan** [persian-tools/persian-tools#42]
@ali-master

I've read the source of the project, and I realize the project missing `Error handling`.
what your think about that.

I'm looking forward to hearing from you.

**Comment by ali-master** [comment]
Your right, can you help us to improve the error handing?

**Comment by masoudDaliriyan** [comment]
of course, we can start with missing arguments and Type errors.
instead of return null.

**Comment by masoudDaliriyan** [comment]
I'll make PR for that and working on it
