### ISSUE TITLE
Proposal: Support for numberplate

### ISSUE THREAD

**Issue by mediv0** [persian-tools/persian-tools#43]
**Is your feature request related to a problem? Please describe.**
Add support for vehicle number plates

**Describe the solution you'd like**
Getting info about the given numberplate. province code,  type (car or bike), the category that it belongs to (Personal plate, government, military, etc...)

**Describe alternatives you've considered**

**Additional context**

Syntax proposal

**usage**
```javascript
import { Plate } from "....";

const vehicle = new Plate("12گ34511");
// or
const vehicle = new Plate({
  number: 1234511,
  char: "گ"
})
```
Plate class can take string or Object as argument ( in string Farsi character will jump to the end )

**getting info about numberplate**
```javascript
const vehicle = new Plate("12گ34511");

vehicle.info();

/*
  should return: 

  {
    plate: 12 گ 345 ایران 23,
    province: "تهران",
    category: "شخصی",
    type: "موتور سیکلت"
  }
*/
```

**validating number plate**
```javascript
const vehicle = new Plate("12گ34511");

vehicle.isValid();

/*
  Should return true or false
*/
```

@ali-master 
Please let me know what do you think.
if this ok with you I can work on RP

**Comment by ali-master** [comment]
Hi there

Wooow let's see this. Thanks for the proposal 🌹

**Comment by ali-master** [comment]
Do you know how we can extract the details? Does it have a normal format for validation and details?

**Comment by mediv0** [comment]
> Do you know how we can extract the details? Does it have a normal format for validation and details?

things we know:
1. a plate can't have 0 in it
2. car plates have 7 digits in them
3. bicycle has 8 digits
4. in the car plate, the last two digits refer to the province code
5. in the bike plate, the first three digits refer to the province code
6. in the car plate, characters like `ب, ث, الف` have meaning.  so we have to check if the given character exists in the list or not
for example 
`ث => خودرو سپاه`
`الف => دولتی`

**Comment by ali-master** [comment]
Do you have a complete list of chars map meaning?

**Comment by mediv0** [comment]
> Do you have a complete list of chars map meaning?

yes
also province codes  with their cities

for reference [province codes](https://apahkam.ir/%D9%85%D8%B9%D8%B1%D9%81%DB%8C-%D8%B4%D9%85%D8%A7%D8%B1%D9%87-%D9%BE%D9%84%D8%A7%DA%A9-%D9%87%D8%A7%DB%8C-%D8%AE%D9%88%D8%AF%D8%B1%D9%88-%D9%87%D8%A7%DB%8C-%D9%85%D8%AE%D8%AA%D9%84%D9%81-%D8%A8/)

**Comment by ali-master** [comment]
Can you implement it?

**Comment by mediv0** [comment]
> Can you implement it?

yep, working on RP
