### ISSUE TITLE
تبدیل حروف به عدد

### ISSUE THREAD

**Issue by omidgolparvar** [persian-tools/persian-tools#57]
<div dir="rtl">
سلام.

درباره یه موردی یه سوال برام ایجاد شد. 
توی Readme درباره تبدیل حروف به عدد، این مورد نوشته شده:

<code dir="ltr">
WordsToNumber.convert("دوازده هزار بیست دو", { digits: "fa" }) // ۱۲۰۲۲
</code>

۱- اعداد در واقع با جداکننده «**و**» بیان میشن مثلا همین عدد ۱۲۰۲۲ رو اگه کسی بخواد به حروف بنویسه، بصورت «دوازده هزار **و** بیست **و** دو» می‌نویسه. این حالت، در واقع حالت استاندارد هست؛ و مثلا NumberFormatter زبان سوییفت، به همین صورت و با «و» اعداد رو به حروف تبدیل می‌کنه. چون بهرحال مفهوم «دوازده هزار بیست دو» می‌تونه متفاوت باشه. مثلا اگه توی مکالمه همچین عبارتی گفته بشه، برداشت‌های زیر ممکنه رخ بده:

- دوازده هزار _|_ بیست _|_ دو : ۱۲۰۰۰ _|_ ۲۰ _|_ ۲
- دوازده _|_ هزار _|_ بیست _|_ دو : ۱۲ _|_ ۱۰۰۰ _|_ ۲۰ _|_ ۲

اما اگه عبارت «دوازده هزار و بیست و دو» گفته بشه، فقط مفهوم عددی «۱۲۰۲۲» رو می‌رسونه.
در نتیجه به نظر این مورد باید مورد بازبینی قرار بگیره.

</div>

**Comment by mediv0** [comment]
<div dir="rtl">
سلام
من فکر نمیکنم این باگ باشه دقیقا همونطور که قرار بوده داره عمل میکنه.

چه با جدا کننده `و` نوشته بشه چه نشه، مقدار خروجی یکی خواهد بود

</div>

```js
WordsToNumber.convert("دوازده هزار بیست دو", { digits: "fa" }); // ۱۲۰۲۲
WordsToNumber.convert("دوازده هزار و بیست و دو", { digits: "fa" }); // ۱۲۰۲۲
```

<div dir="rtl">

و وقتی شما توی یه عدد یکان، دهگان و... دارید قطعا اون عدد رو دیگه تیکه تیکه نمیخونید

البته این مورد که گفتید قابل حل هست. البته فکر نمیکنم ضروری باشه

</div>

**Comment by ali-master** [comment]
سلام از من

همونطور که مهدی جان هم گفت، تابع هر دو حالت رو متوجه میشه اما یه موضوعی پیش میاد.
در نسخه بعدی قابلیتی قرار اضافه بشه که اگر عدد یا متن رو طبق فرمول زیر بهش بدی مقادیر رو  این شکلی خروجی میده که بیشتر مصارف بانکی داره بنظرم.

#### WordsToNumber
```js
WordsToNumber.convert("۱۲ هزار و ۲۲", { digits: "fa", mode: "simple" }); // ۱۲۰۲۲
WordsToNumber.convert("۱۲ هزار ۲۲", { digits: "fa", mode: "simple" }); // ۱۲۰۲۲
```
#### NumberToWords
```js
NumberToWords.convert("12022", { digits: "fa", mode: "simple" }); // ۱۲ هزار و ۲۲
```

**Comment by mediv0** [comment]
closed due to inactivity
