### ISSUE TITLE
در نظر گرفتن اعشار در کاما

### ISSUE THREAD

**Issue by faridfr** [persian-tools/persian-tools#59]
https://github.com/persian-tools/persian-tools/blob/35422fc5bf6f85642dc1c5ffc71d1ebe31d9bafa/test/addCommas.spec.ts#L6

<p dir="rtl">
بنظرم بهتره در تست ها اعشار در کاما در نظر گرفته شود<br>
مثال :  30,000,000.02
</p>

**Comment by mediv0** [comment]
من دارم تست ها رو برسی میکنم تا بتونیم پوشش کد ها رو افزایش بدیم
اگه دوست داشتی میتونی پول ریکوئست بدی. اگه نه که من این مورد رو هم با اجازه علی اضافه میکنم

**Comment by ali-master** [comment]
مرس مهدی جان از پیشنهاد خوبی که دادی، بله این مشکل توی کد نسخه تایپ اسکریپت وجود داره

@mediv0 
مهدی جان وقتش رو داری که فیکسش کنی؟

**Comment by mediv0** [comment]
> مرس مهدی جان از پیشنهاد خوبی که دادی، بله این مشکل توی کد نسخه تایپ اسکریپت وجود داره
> 
> @mediv0
> مهدی جان وقتش رو داری که فیکسش کنی؟

اره مشکلی نداره
