### ISSUE TITLE
Request : a shared json file that contains constants

### ISSUE THREAD

**Issue by faridfr** [persian-tools/persian-tools#64]
<p dir="rtl">
لطفا حالات زیر را در نظر بگیرید
</p>
<p dir="rtl">
اگر یک سرشماره به سرشماره های همراه اول اضافه بشه همه ی ما باید ریپازیتوری هامون رو اپدیت کنیم 
</p>
<p dir="rtl">
برای شهر و استان ها هم این اتفاق میفته
</p>
<p dir="rtl">
توی php اگر بخوایم سینتکس شبیه پکیج اصلی در بیاد باید از Trait استفاده کنیم که توی trait نمیشه constant تعریف کرد . همینطور امکان استفاده از متغیرهای کلاس هنگام تعریف یک متغیر دیگه نیست . این مباحث راه حل دارن و در پول ریکوئست آخر حتی به پیاده سازی پرداخته میشه
</p>
<p dir="rtl">
همچنین در برخی موارد ناهماهنگی های فولدربندی در بین پروژه ها بابت این ثابت ها بوجود اومده . بعضیا درون فولدر جدا . بعضیا یک فایلی ها جدا چند فایلی ها کنار هم و ...
</p>
<p dir="rtl">
اما حس کردم یک جای کار بابت موارد بالا میلنگه و چه خوب میشد یه فایل json واحدی وجود می داشت که مثل یک asset استفاده میکردیم و اپدیتش هم میکردیم راحت . ما به پیاده سازی ادامه میدیم اما دوست داشتم نظرتونو در این مورد بدونم که ایا راهی وجود داره یا نه . شایدم این مورد حساسیت الکی باشه
</p>
<p dir="rtl">
فایل های json میتونن با یک action cronjob طوری آپدیت بشن
</p>

**Comment by ali-master** [comment]
سلام فرید جان،

موردی که گفتی رو خیلی باهات موافقم و بنظرم هم که خیلی لازمه، من بچه ها رو اساین کردم که اونا هم پیشنهادشون رو نسبت به این موضوع بدن

**Comment by mediv0** [comment]
این حرکتا وقتی خوبه که مثلا شما فایل های زیادی دارید و هروز هم ممکنه تغییرات توش انجام بشه و شما نمیتونی دستی مثلا 50 تا فایل که هرکدوم 100 خط اضافه شده رو آپدیت کنی.

اونجا میشه اسکریپت نوشت که همه فایلا اپدیت کنه

ولی اینجا کد شهر و مرکز استان و همراه اول اینا تغییر نمیکنه. اگه کد جدید هم اضافه بشه نهایتش 1 یا 2 تا خواهد بود

**Comment by EhsanAramide** [comment]
منم با مهدی موافقم فکر نمیکنم همراه اول یا هر اوپراتور دیگ ای تعداد خیلی زیادی سرشماره اضافه کنه نهایتش در کل سال یکی دوتا باشه در تعداد بالا مثلا ۵۰ تا این ایده ی عالیه ایه اما یکی دوتا رو اضافه میکنیم موردی نداره بازم نظر جمع مهمتره =)

**Comment by faridfr** [comment]
@EhsanAramide  @mediv0 

بحث زمان رو هم در نظر بگیرید لطفا . اگر هر کدوممون قرار باشه وقت زیادی بزاریم برای این ثابت ها بنظرتون جالبه ؟ این فایل رو ببینین : 
https://github.com/persian-tools/persian-tools/blob/master/src/modules/phoneNumber/utils.ts
داریم قشنگ خودمون رو تکرار میکنیم .

من فکر کردم اگر وقت بزاریم پکیج ها رو یکدست کنیم و به یه نقطه برسونیم ... با یه اتفاق این چنینی یهو همشون از یکدستی در میان
ولی خب حرف شما هم درسته . **الان** شاید لازم نباشه .

**Comment by moeindev** [comment]
منم موافقم که از ی فرمت و ساختار استفاده کنیم، من این فایلو از ی جای دیگه برداشتم ولی به نظرم اصلا جالب نیست: 
https://github.com/persian-tools/kotlin-persian-tools/blob/feature-validators/src/main/resources/carrier.json

**Comment by EhsanAramide** [comment]
> من فکر کردم اگر وقت بزاریم پکیج ها رو یکدست کنیم و به یه نقطه برسونیم ... با یه اتفاق این چنینی یهو همشون از یکدستی در میان
> ولی خب حرف شما هم درسته . **الان** شاید لازم نباشه .

در دارت برای بحث کراس پلتفرمی ک داره هم در وب هم روی ماشین چون استفاده میشه اگر آبجکت دارت نباشه به همون میزان که وقت میزاریم برای تبدیلش کاستنت ها به آبجکت های دارت باید همون میزانم وقت بزاریم تا کدبنویسیم برای خوندن فایل جیسان در هر پلتفرم ، هم وب هم وی اِم و عملا زمان بیشتری رو میگیره
بازم میگم نظر جمع مهم تره

**Comment by faridfr** [comment]
@EhsanAramide 

این فایل رو توی دارت اماده کردین ؟
https://github.com/persian-tools/persian-tools/blob/master/src/modules/getPlaceByIranNationalId/nationalId.skip.ts

**Comment by EhsanAramide** [comment]
@faridfr 
ن ولی اگر به لحاظ طولانی بودن فایل میگید زمانی نمیبره کپی پیسته و خب ابزار های توسعه اینقدری پیشرفت کردن که پورت کردن این فایل اونقدرا زمان بر نیست 
من صحبتی که دارم الان سر اینکه اگر از پکیج بخواد در وب و فلاتر و روی ماشین در سمت سرور اجرا بشه باید ببینیم به چه صورت میشه مشکل رو حل کرد (اگر از فایل جیسان استفاده کرد) اگر فکر میکنید خیلی اذیت کنندس پورت کردنش باید دنبال این باشیم ک چجوری میشه این مورد رو در بحث کراس پلتفرم بودن علل خصوص سره فلاتر حل کرد 
بررسی میکنیم منشن میکنیم در اسلک
البته
https://github.com/persian-tools/persian-tools/blob/master/src/modules/sheba/codes.skip.ts
من خودم آرایه موجود در این فایل رو با چند خط کد کلا تبدیلش کردن به این فایل و کلا شد آبجکتی از کلاس های دارت
https://github.com/persian-tools/dart-persian-tools/blob/feature/sheba/lib/src/constants/sheba/constants.dart
البته ابزارم اینتلیجی کامیونیتی ادیشن بود

**Comment by nimahkh** [comment]
<span dir="rtl" >
من موافق این ایده نیستم. ما زبان های مختلف و ریپو های مختلف داریم . این که همه زیر مجموعه یک ریپو هستیم، دلیل بر هندشیک نیست. 
موردی که در PHP میگید درسته. اما راهکار هایی هم برای این مورد است . مثل اینکه شما ثابت ها را در جایی به عنوان کانفیگ تعریف کنید . در گولنگ به شکل دیگه و در دارت هم همینطور. پس نمیتونیم با یک دید به سمت همه بریم. هدف اینه که پکیج هماهنگ باشه و درست کار کنه. گاهی اوقات راه کاری که میگید، سربار ایجاد میکنه. وقتی که داخل گولنگ با یک تایپ تعریف کردن همه چیز درست انجام میشه، چرا بیام یک جیسون رو دیکد کنم و بعدش همون تایپ ها رو ایجاد کنم؟ 
هم پکیجم رو سنگین کردم و هم پروسه عملیات رو. 
به نظرم هر زبانی باید با روش خودش بره جلو و نمیشه یک دیدگاه رو برای همه استفاده کنیم. از نظر معماری، به مشکل میخوریم. 
</div>
