### ISSUE TITLE
National ID digits can/can't be the same ?

### ISSUE THREAD

**Issue by faridfr** [persian-tools/persian-tools#65]
https://github.com/persian-tools/persian-tools/blob/b26c9ba9fe2355d4e2071a3de62be6774f277217/test/verifyIranianNationalId.spec.ts#L11

<p dir="rtl">
دوستان اون بنده خدایی که میخواست کد ملیشو عوض کنه عوض نکرد ؟
توی خیلی از سیستم ها این کد ملی رو نامعتبر میشناسن  . از این کد و کدهای مشابه سو استفاده نمیشه ؟
</p>

**Comment by ali-master** [comment]
در حقیقت این یک باگ نیست، این مشکل هنوز پاربرجاست و انگار آدم های دیگه ای هم هستن که این مشکل رو دارن،

**Comment by faridfr** [comment]
@ali-master
اوکی ممنون. پس منم این محدودیت رو برمیدارم
