### ISSUE TITLE
card number validation

### ISSUE THREAD

**Issue by faridfr** [persian-tools/persian-tools#66]
<p dir="rtl">
<b>6219861034529007002229988112233</b><br>
این شماره کارت طبق الگوریتم شما معتبر است ؟<br>
16 رقم اول آن معتبر است اما بقیه اعداد الکی هست<br>
ممکنه شماره کارت بیشتر از 16 رقم باشه ولی محدودیت داره و بازم هر چیزی نمیتونه باشه درست میگم ؟
</p>

**Comment by ali-master** [comment]
فکر میکنم regex ای که نوشته بودیم این رو قبول کنه. یه تست میکنم بهت میگم.
