### ISSUE TITLE
Convert 0 to Persian digit

### ISSUE THREAD

**Issue by SarahShkb** [persian-tools/persian-tools#70]
**Describe the bug**
Hi and thanks for this great and useful project.
The issues is when function `digitsEnToFa` is called to convert digit 0, it returns undefined. it works fine for numbers contain 0, but returns undefined for 0 itself.

**To Reproduce**
`digitsEnToFa(0)`

**Expected behavior**
the function should return ۰ .

 thanks again!

**Comment by ali-master** [comment]
Hi @SarahShkb ,

Thanks for using the PersianTools. 

I will fix the bug as soon as posible and also refactor the related codes and tests to make sure all functionalities work as well as expected.

If you have any other suggestion, We are all ears.

**Comment by SarahShkb** [comment]
Thanks a lot for your response!

**Comment by ali-master** [comment]
This issue has fixed and will be available in the next release. We will inform you after new version released.

**Comment by ali-master** [comment]
New beta version released. Check it out
[https://www.npmjs.com/package/@persian-tools/persian-tools/v/1.6.0-beta.6](https://www.npmjs.com/package/@persian-tools/persian-tools/v/1.6.0-beta.6)

Update to the latest version:
```bash
npm i --save @persian-tools/persian-tools@latest
```

**Comment by SarahShkb** [comment]
Great! when will it be merged?

**Comment by ali-master** [comment]
New version has released which means it has merged and also published to the npm registry and ready to install.

**Comment by SarahShkb** [comment]
Got it! Thanks!
