### ISSUE TITLE
Please verify that the package.json has a valid "main" entry

### ISSUE THREAD

**Issue by mohammadizanloo55** [persian-tools/persian-tools#75]
![problem1](https://user-images.githubusercontent.com/54350937/115904168-b800f280-a479-11eb-8655-6a1d305736f3.png)
![problem2](https://user-images.githubusercontent.com/54350937/115904188-bdf6d380-a479-11eb-9b41-89daf42ab182.png)
node js v14.15.3
my os : Ubuntu 20.04
i  install package with yarn

**Comment by mediv0** [comment]
you can import cjs file directly from the build folder

```js
const tools = require("@persian-tools/persian-tools/build/persian-tools");
// ...
```

**Comment by mediv0** [comment]
@ali-master we should change the main entry from 
```js
"main": "./build/persian-tools.cjs.js",
```
to
```js
"main": "./build/persian-tools.js",
```

The current build script doesn't produce `persian-tools.cjs.js`

**Comment by ali-master** [comment]
Hi @mohammadizanloo55 

v1.6.1 just released.

```bash
npm i --save @persian-tools/persian-tools@latest
```

**Comment by mohammadizanloo55** [comment]
![Screenshot_2021-04-18_10-46-22](https://user-images.githubusercontent.com/54350937/115944326-5452e580-a4ca-11eb-8b4f-c09cee5cd153.png)
Thanks for the great support ❤️
