### ISSUE TITLE
Persian Remained Time

### ISSUE THREAD

**Issue by pshaddel** [persian-tools/persian-tools#76]
In many projects we have a persian count down but we have to implement it somehow to get the remained minutes remained hours, days, etc.

A function like this will solve this issue:
```javascript
remainedTime("2019-01-01 03:01:45") = {
Century: 0,
Year: 2,
Month: 4,
Day: 3,
Hour: 5
Minure: 2,
Second: 20
};
```
remainedTime("2019-01-01 03:01:45").toString() = "۲ سال و ۴ ماه و ۳ روز ۵ ساعت و ۲ دقیقه و بیست ثانیه"

If you consider this function useful, I think I can start working on this issue.

**Comment by ali-master** [comment]
It's good feature and let's start implementing, but before starting, we have to arrange a meeting for talking about this feature details.

**Comment by pshaddel** [comment]
> It's good feature and let's start implementing, but before starting, we have to arrange a meeting for talking about this feature details.

Sure. use this link: https://join.skype.com/invite/m7RqmeIfrpsm

**Comment by pshaddel** [comment]
@ali-master علی جان اینم هر وقت فرصت داشتی بیا حرف بزنیم

**Comment by ali-master** [comment]
سلام از من @pshaddel 

بنظرم شروعش کن پورشاد جان
