### ISSUE TITLE
Refactor README

### ISSUE THREAD

**Issue by masoudDaliriyan** [persian-tools/persian-tools#80]
Hey guys,
there are a lot of extra examples in  "README". in many validating functions, 1 or 2 examples is enough. I think we should remove extra examples to make "README" more clear.

**Comment by ali-master** [comment]
Hi @masoudDaliriyan

Let's clean it if yo have time to do.

**Comment by masoudDaliriyan** [comment]
@ali-master  I will create some PR for this.
