### ISSUE TITLE
Converting a date into a time ago

### ISSUE THREAD

**Issue by hasanisaeed** [persian-tools/persian-tools#85]
Hi guys
Thanks for this magnificent tool.
I have a class in my project to convert a date into a time ago as follows:

datetime | time ago
-- | -- 
0 - 59 seconds | چند ثانیه قبل
..|..
22 - 36 hours | یک روز قبل
25 - 45 days | یک ماه پیش
..|..
546 days+ | N سال قبل

I would like this feature to be in this tool as well.

**Comment by ali-master** [comment]
Hi @realsaeedhassani 

It would be great if you write it by yourself and I appreciate it a lot.
