### ISSUE TITLE
TS declaration file....

### ISSUE THREAD

**Issue by amirqasemi74** [persian-tools/persian-tools#9]
can you provide any declaration file for this repo?

**Comment by ali-master** [comment]
Why we need that?

**Comment by amirqasemi74** [comment]
I am using typescript and your repo does not have .d.ts file so i can't import any of functions...

**Comment by ali-master** [comment]
I got it. thanks

**Comment by ali-master** [comment]
Published to npm(v.1.2.1)

**Comment by amirqasemi74** [comment]
I checked it. you have not put .d.ts files to the repo

**Comment by ali-master** [comment]
I appreciate it if you do it by yourself. I have no time these days.

**Comment by moh3n9595** [comment]
It seems to be fixed.

**Comment by ali-master** [comment]
Good job @moh3n9595 jan. I appreciate your collaboration.
