### ISSUE TITLE
Node Engine Problem 

### ISSUE THREAD

**Issue by amirzenoozi** [persian-tools/persian-tools#99]
**Describe the bug**
I try to install the Latest version of `persian-tools` in my projects but I got this error :

```shell
 @persian-tools/persian-tools@1.6.2: The engine "node" is incompatible with this module. Expected version ">=12<16". Got "14.16.0"
```

I have this issue in `v14.0`, `v14.15.0` , `v14.16.0`

**Comment by amirzenoozi** [comment]
i think we have to replace: 
```json
"engines": {
	"node": ">=12<16",
	"npm": ">=7"
}
```

with:  
```json
"engines": {
	"node": ">=12 <16",
	"npm": ">=7"
}
```
by adding space

**Comment by ali-master** [comment]
Thanks for reporting, I'll fix it today.

**Comment by ali-master** [comment]
v1.6.3 just released

**Comment by amirzenoozi** [comment]
it solves
